import Icons from './constants/Icons';



export const skills = [
  'JavaScript',
  'VSC',
  'UI/UX Design',
  'Node.js',
  'Firebase',
  'TypeScript',
  'JavaScript',
  'VSC',
  'UI/UX Design',
  'Node.js',
  'Firebase',
  'TypeScript',
  'JavaScript',
  'VSC',
  'UI/UX Design',
  'Node.js',
  'Firebase',
  'TypeScript',
];


export const data = [
  {label: 'JavaScript', value: '1'},
  {label: 'React Native', value: '2'},
  {label: 'Python', value: '3'},
  {label: 'Java', value: '4'},
  {label: 'Node.js', value: '5'},
  {label: 'TypeScript', value: '6'},
  {label: 'Ruby', value: '7'},
  {label: 'Django', value: '8'},
  {label: 'PHP', value: '9'},
  {label: 'Go', value: '10'},
];
export const deptData = [
  {label: 'Mobile & Apps', value: '1'},
  {label: 'Apps 2', value: '2'},
  {label: 'Apps 1', value: '3'},
  {label: 'DevOps', value: '4'},
  {label: 'Human Resources', value: '5'},
  {label: 'Finance & IT', value: '6'},
  {label: 'Marketing & Sales', value: '7'},
  {label: 'AI & ML', value: '8'},
  {label: 'QA', value: '9'},
];

export const forYouPosts = [
  { id: '1', image: Icons.instaPost1, userName: 'Ishika', profilePicture: Icons.profilePicture1 },
  { id: '2', image: Icons.instaPost2, userName: 'Akshita', profilePicture: Icons.profilePicture2 },
  { id: '3', image: Icons.instaPost3, userName: 'Ishita', profilePicture: Icons.profilePicture3 },
  { id: '4', image: Icons.instaPost4, userName: 'Devanshi', profilePicture: Icons.profilePicture4 },
  { id: '5', image: Icons.instaPost5, userName: 'Ravi', profilePicture: Icons.profilePicture5 },
  { id: '6', image: Icons.instaPost6, userName: 'Sanya', profilePicture: Icons.profilePicture6 },
  { id: '7', image: Icons.instaPost7, userName: 'Ananya', profilePicture: Icons.profilePicture7 },
  { id: '8', image: Icons.instaPost8, userName: 'Manav', profilePicture: Icons.profilePicture8 },
  { id: '9', image: Icons.instaPost9, userName: 'Raj', profilePicture: Icons.profilePicture9 },
  { id: '10', image: Icons.instaPost10, userName: 'Priya', profilePicture: Icons.profilePicture10 },
  { id: '11', image: Icons.instaPost11, userName: 'Simran', profilePicture: Icons.profilePicture11 },
  { id: '12', image: Icons.instaPost12, userName: 'Amit', profilePicture: Icons.profilePicture12 },
  { id: '13', image: Icons.instaPost5, userName: 'Ravi', profilePicture: Icons.profilePicture5 },
  { id: '14', image: Icons.instaPost6, userName: 'Sanya', profilePicture: Icons.profilePicture6 },
  { id: '15', image: Icons.instaPost7, userName: 'Ananya', profilePicture: Icons.profilePicture7 },
  { id: '16', image: Icons.instaPost8, userName: 'Manav', profilePicture: Icons.profilePicture8 },
  { id: '17', image: Icons.instaPost9, userName: 'Raj', profilePicture: Icons.profilePicture9 },
  { id: '18', image: Icons.instaPost10, userName: 'Priya', profilePicture: Icons.profilePicture10 },
  { id: '19', image: Icons.instaPost11, userName: 'Simran', profilePicture: Icons.profilePicture11 },
  { id: '20', image: Icons.instaPost12, userName: 'Amit', profilePicture: Icons.profilePicture12 },
];

export const posts = [
  {
    id: '1',
    userName: 'Ishika Shahaney',
    profilePicture: Icons.profilePicture1,
    postImage: Icons.instaPost1,
    caption: 'Enjoying a sunny day! 🌞🌿',
  },
  {
    id: '2',
    userName: 'Akshita Sharma',
    profilePicture: Icons.profilePicture2,
    postImage: Icons.instaPost2,
    caption: 'Weekend vibes! 🏖️',
  },
  {
    id: '3',
    userName: 'Ishita Porwal',
    profilePicture: Icons.profilePicture3,
    postImage: Icons.instaPost3,
    caption: 'Exploring new places! 🌍✈️',
  },
  {
    id: '4',
    userName: 'Devanshi Tiwari',
    profilePicture: Icons.profilePicture4,
    postImage: Icons.instaPost4,
    caption: 'Life is better with friends! 👯‍♀️',
  },
  {
    id: '5',
    userName: 'Ravi Kumar',
    profilePicture: Icons.profilePicture5,
    postImage: Icons.instaPost5,
    caption: 'Chasing sunsets 🌅✨',
  },
  {
    id: '6',
    userName: 'Sanya Mehta',
    profilePicture: Icons.profilePicture6,
    postImage: Icons.instaPost6,
    caption: 'Coffee and good vibes ☕💫',
  },
  {
    id: '7',
    userName: 'Ananya Singh',
    profilePicture: Icons.profilePicture7,
    postImage: Icons.instaPost7,
    caption: 'A walk in nature 🍃🌿',
  },
  {
    id: '8',
    userName: 'Manav Agarwal',
    profilePicture: Icons.profilePicture8,
    postImage: Icons.instaPost8,
    caption: 'Making memories 🗺️💙',
  },
  {
    id: '9',
    userName: 'Raj Verma',
    profilePicture: Icons.profilePicture9,
    postImage: Icons.instaPost9,
    caption: 'Sunset vibes 🌅🌊',
  },
  {
    id: '10',
    userName: 'Priya Yadav',
    profilePicture: Icons.profilePicture10,
    postImage: Icons.instaPost10,
    caption: 'Stay positive and work hard 💪😊',
  },
  {
    id: '11',
    userName: 'Simran Kaur',
    profilePicture: Icons.profilePicture11,
    postImage: Icons.instaPost11,
    caption: 'Good times and tan lines 🏖️🌞',
  },
  {
    id: '12',
    userName: 'Amit Singh',
    profilePicture: Icons.profilePicture12,
    postImage: Icons.instaPost12,
    caption: 'Family first! ❤️👨‍👩‍👧‍👦',
  },
  {
    id: '13',
    userName: 'Nisha Rathi',
    profilePicture: Icons.profilePicture1,
    postImage: Icons.instaPost1,
    caption: 'Weekend getaways are the best! 🏞️',
  },
  {
    id: '14',
    userName: 'Karan Rajput',
    profilePicture: Icons.profilePicture2,
    postImage: Icons.instaPost2,
    caption: 'Breezy afternoons and chilled vibes 🌬️🍃',
  },
  {
    id: '15',
    userName: 'Aditi Sharma',
    profilePicture: Icons.profilePicture3,
    postImage: Icons.instaPost3,
    caption: 'A day well spent ☀️🌳',
  },
];

export const chatData = [
  {id: '1', profilePicture: Icons.profilePicture1, name: 'Ishika', lastMessage: 'Hello!', time: '2:00 PM', unreadCount: 2},
  {id: '2', profilePicture: Icons.profilePicture2, name: 'Ayushi', lastMessage: 'See you soon.', time: '1:45 PM', unreadCount: 0},
  {id: '3', profilePicture: Icons.profilePicture3, name: 'Rahul', lastMessage: 'Thanks!', time: '12:30 PM', unreadCount: 5},
  {id: '4', profilePicture: Icons.profilePicture4, name: 'Ananya', lastMessage: 'Let’s catch up!', time: '11:00 AM', unreadCount: 1},
  {id: '5', profilePicture: Icons.profilePicture5, name: 'Nisha', lastMessage: 'Good morning!', time: '10:00 AM', unreadCount: 3},
  {id: '6', profilePicture: Icons.profilePicture6, name: 'Manish', lastMessage: 'Are you free today?', time: '9:30 AM', unreadCount: 0},
  {id: '7', profilePicture: Icons.profilePicture7, name: 'Amit', lastMessage: 'Got the files you sent.', time: '8:45 AM', unreadCount: 4},
  {id: '8', profilePicture: Icons.profilePicture8, name: 'Simran', lastMessage: 'Check the email I forwarded.', time: '8:00 AM', unreadCount: 2},
  {id: '9', profilePicture: Icons.profilePicture9, name: 'Karan', lastMessage: 'Happy birthday!', time: '7:30 AM', unreadCount: 0},
  {id: '10', profilePicture: Icons.profilePicture10, name: 'Deepak', lastMessage: 'Where is the report?', time: '7:00 AM', unreadCount: 6},
  {id: '11', profilePicture: Icons.profilePicture11, name: 'Madhuri', lastMessage: 'Are we still meeting?', time: '6:30 AM', unreadCount: 1},
  {id: '12', profilePicture: Icons.profilePicture1, name: 'Shivani', lastMessage: 'Got your message.', time: '6:00 AM', unreadCount: 0},
  {id: '13', profilePicture: Icons.profilePicture2, name: 'Vikram', lastMessage: 'How are you doing?', time: '5:30 AM', unreadCount: 2},
  {id: '14', profilePicture: Icons.profilePicture3, name: 'Pooja', lastMessage: 'See you at the event!', time: '5:00 AM', unreadCount: 0},
  {id: '15', profilePicture: Icons.profilePicture4, name: 'Ravi', lastMessage: 'Let’s grab lunch today.', time: '4:30 AM', unreadCount: 5},
];

export const groupData = [
  {
    id: 1,
    members: [
      {id: 1, name: 'Alice', profilePicture: Icons.profilePicture1},
      {id: 2, name: 'Bob', profilePicture: Icons.profilePicture2},
      {id: 3, name: 'Charlie', profilePicture: Icons.profilePicture3},
    ],
    lastMessage: 'Let’s meet tomorrow.',
    time: '10:45 AM',
    unreadCount: 3,
  },
  {
    id: 2,
    groupName: 'Report Review',
    members: [
      {id: 1, name: 'Sonia', profilePicture: Icons.profilePicture4},
      {id: 2, name: 'Vikram', profilePicture: Icons.profilePicture5},
      {id: 3, name: 'Deepak', profilePicture: Icons.profilePicture6},
    ],
    lastMessage: 'Check the latest report.',
    time: '9:30 AM',
    unreadCount: 0,
  },
  {
    id: 3,
    groupName: 'Lunch Planning',
    members: [
      {id: 1, name: 'Madhuri', profilePicture: Icons.profilePicture7},
      {id: 2, name: 'Ravi', profilePicture: Icons.profilePicture8},
      {id: 3, name: 'Priya', profilePicture: Icons.profilePicture9},
    ],
    lastMessage: 'Lunch today?',
    time: '8:15 AM',
    unreadCount: 4,
  },
  {
    id: 4,
    groupName: 'Project Discussion',
    members: [
      {id: 1, name: 'Karan', profilePicture: Icons.profilePicture10},
      {id: 2, name: 'Simran', profilePicture: Icons.profilePicture11},
      {id: 3, name: 'Harsh', profilePicture: Icons.profilePicture1},
    ],
    lastMessage: 'Project deadline tomorrow.',
    time: '7:45 AM',
    unreadCount: 1,
  },
  {
    id: 5,
    groupName: 'Meeting Updates',
    members: [
      {id: 1, name: 'Amit', profilePicture: Icons.profilePicture2},
      {id: 2, name: 'Shivani', profilePicture: Icons.profilePicture3},
      {id: 3, name: 'Pooja', profilePicture: Icons.profilePicture4},
    ],
    lastMessage: 'Meeting postponed.',
    time: '6:30 AM',
    unreadCount: 2,
  },
  {
    id: 6,
    groupName: 'Catch Up Group',
    members: [
      {id: 1, name: 'Harsh', profilePicture: Icons.profilePicture5},
      {id: 2, name: 'Ravi', profilePicture: Icons.profilePicture6},
      {id: 3, name: 'Neha', profilePicture: Icons.profilePicture7},
    ],
    lastMessage: 'Catch up soon!',
    time: '6:00 AM',
    unreadCount: 0,
  },
  {
    id: 7,
    groupName: 'Work Updates',
    members: [
      {id: 1, name: 'Simran', profilePicture: Icons.profilePicture8},
      {id: 2, name: 'Alice', profilePicture: Icons.profilePicture9},
      {id: 3, name: 'Karan', profilePicture: Icons.profilePicture10},
    ],
    lastMessage: 'Work updates for today.',
    time: '5:30 AM',
    unreadCount: 5,
  },
  {
    id: 8,
    groupName: 'Project Proposal',
    members: [
      {id: 1, name: 'Ritika', profilePicture: Icons.profilePicture11},
      {id: 2, name: 'Vikram', profilePicture: Icons.profilePicture1},
      {id: 3, name: 'Ananya', profilePicture: Icons.profilePicture2},
    ],
    lastMessage: 'Review the project proposal.',
    time: '4:15 AM',
    unreadCount: 1,
  },
  {
    id: 9,
    groupName: 'Team Meeting',
    members: [
      {id: 1, name: 'Amit', profilePicture: Icons.profilePicture3},
      {id: 2, name: 'Sonia', profilePicture: Icons.profilePicture4},
      {id: 3, name: 'Deepak', profilePicture: Icons.profilePicture5},
    ],
    lastMessage: 'Important: Team meeting tomorrow.',
    time: '3:45 AM',
    unreadCount: 2,
  },
  {
    id: 10,
    groupName: 'Report Updates',
    members: [
      {id: 1, name: 'Ravi', profilePicture: Icons.profilePicture6},
      {id: 2, name: 'Alice', profilePicture: Icons.profilePicture7},
      {id: 3, name: 'Shivani', profilePicture: Icons.profilePicture8},
    ],
    lastMessage: 'I’ll send you the updated report.',
    time: '3:00 AM',
    unreadCount: 0,
  },
];


export const newChatData = [
  {id: '1', profilePicture: Icons.profilePicture1, name: 'Ishika', bio: 'Passionate'},
  {id: '2', profilePicture: Icons.profilePicture2, name: 'Ayushi', bio: 'Innovator'},
  {id: '3', profilePicture: Icons.profilePicture3, name: 'Rahul', bio: 'Developer'},
  {id: '4', profilePicture: Icons.profilePicture4, name: 'Ananya', bio: 'Team Player'},
  {id: '5', profilePicture: Icons.profilePicture5, name: 'Nisha', bio: 'Explorer'},
  {id: '6', profilePicture: Icons.profilePicture6, name: 'Manish', bio: 'Creative Thinker'},
  {id: '7', profilePicture: Icons.profilePicture7, name: 'Amit', bio: 'Problem Solver'},
  {id: '8', profilePicture: Icons.profilePicture8, name: 'Simran', bio: 'Tech Enthusiast'},
  {id: '9', profilePicture: Icons.profilePicture9, name: 'Karan', bio: 'Strategist'},
  {id: '10', profilePicture: Icons.profilePicture10, name: 'Deepak', bio: 'Visionary'},
  {id: '11', profilePicture: Icons.profilePicture11, name: 'Madhuri', bio: 'Achiever'},
  {id: '12', profilePicture: Icons.profilePicture1, name: 'Shivani', bio: 'Thinker'},
  {id: '13', profilePicture: Icons.profilePicture2, name: 'Vikram', bio: 'Collaborator'},
  {id: '14', profilePicture: Icons.profilePicture3, name: 'Pooja', bio: 'Adventurer'},
  {id: '15', profilePicture: Icons.profilePicture4, name: 'Ravi', bio: 'Leader'},
];


export const recentSearch = [
  {id: '1', profilePicture: Icons.profilePicture1, name: 'Ishika', bio: 'Passionate'},
  {id: '2', profilePicture: Icons.profilePicture2, name: 'Ayushi', bio: 'Innovator'},
  {id: '3', profilePicture: Icons.profilePicture3, name: 'Rahul', bio: 'Developer'},
  {id: '4', profilePicture: Icons.profilePicture4, name: 'Ananya', bio: 'Team Player'},
  
];
