import { StyleSheet } from "react-native";
import { Colors } from "../../utils/constants/colors";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FBFBFB',
    },
    content: {
      paddingBottom: 40,
    },
    header: {
      position: 'relative',
      height: 200,
    },
    profileImageContainer: {
      position: 'absolute',
      bottom: -50,
      alignSelf: 'center',
      width: 150,
      height: 150,
      borderRadius: 100,
      borderWidth: 4,
      borderColor: 'white',
      overflow: 'hidden',
    },
    profileImage: {
      width: '100%',
      height: '100%',
      borderRadius: 50,
    },
    detailsContainer: {
      marginTop: 20,
      paddingHorizontal: 20,
      alignItems: 'center',
    },
    editIcon: {
      marginHorizontal: 20,
      marginVertical: 20,
      marginLeft: 'auto',
    },
    name: {
      fontSize: 30,
      fontWeight: 'bold',
      color: Colors.darkBlue,
      marginBottom: 8,
    },
    designation: {
      fontSize: 16,
      color: Colors.darkGray,
      marginBottom: 8,
    },
    bio: {
      fontSize: 16,
      color: Colors.darkGray,
      marginBottom: 8,
      maxWidth: '80%',
      textAlign: 'center',
    },
    description: {
      fontSize: 14,
      color: '#CCC',
      textAlign: 'center',
      marginBottom: 10,
    },
    location: {
      fontSize: 16,
      color: Colors.darkGray,
      marginBottom: 30,
    },
    actionButtons: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      width: '100%',
      marginBottom: 30,
    },
    actionButton: {
      backgroundColor: '#FBFBFB',
      shadowColor: '#000',
      shadowOffset: {width: 30, height: 30},
      shadowOpacity: 2,
      shadowRadius: 10,
      elevation: 10,
      width: '45%',
      height: 50,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      paddingHorizontal: 10,
    },
    actionButtonText: {
      fontSize: 18,
      color: Colors.darkBlue,
      fontWeight: '600',
      textAlign: 'center',
      marginLeft: 5,
    },
    icon: {
      marginRight: 5,
    },
    iconButton: {
      backgroundColor: '#FBFBFB',
      shadowColor: '#000',
      shadowOffset: {width: 30, height: 30},
      shadowOpacity: 2,
      shadowRadius: 10,
      elevation: 10,
      padding: 15,
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: -10,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.darkBlue,
      letterSpacing: 1,
      marginBottom: 20,
      marginLeft: 10,
      marginTop: 10,
    },
    skillsBox: {
      width: '100%',
      padding: 15,
      borderRadius: 10,
      marginTop: 10,
      backgroundColor: '#FBFBFB',
      shadowColor: '#000',
      shadowOffset: {width: 30, height: 30},
      shadowOpacity: 2,
      shadowRadius: 10,
      elevation: 10,
    },
    skillsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-evenly',
      width: '100%',
    },
  
    skillTab: {
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 20,
      margin: 5,
      minWidth: 80,
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FBFBFB',
      borderWidth: 1,
      borderColor: Colors.darkBlue,
    },
    skillText: {
      fontSize: 14,
      color: '#004080',
    },
    toggleButton: {
      marginTop: 20,
      alignItems: 'center',
    },
    toggleButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: Colors.darkBlue,
    },
    loadingOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      zIndex: 10,
    },
  });
  